### ISSUE TITLE
Error when Launching on Linux "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by resolutezach1** [zeropolis79/PETSCIIRobots-SDL#7]
So I Compiled Petscii Robots SDL on my Windows PC via SDL which compiled the Version for Linux, But when I copied the Game onto my Steam Deck it wouldn't launch for some reason, I opened Konsole in the Folder where I copied the Game to, then when I tried to launch the Game again, it gave me this Error, "Segmentation fault (core dumped)". Is there a Fix for this? or is there something wrong with the Game's Code?

**Comment by polluks** [comment]
Did you apply #3?

**Comment by zeropolis79** [comment]
I can't because I don't know how to do it but I'll talk to teh person who did write it

**Comment by resolutezach1** [comment]
> @resolutezach1 Did you apply #3?

No, I Didn't, but I'll try it to see if that fixes the issue.

**Comment by resolutezach1** [comment]
> @resolutezach1 Did you apply #3?

I just tried it, it didn't work. :(

**Comment by zeropolis79** [comment]
I've got some things to do until at least 2PM (UK time) but when I get back, I'll contact the coder and see what I can find out

**Comment by nolemretaWxd** [comment]
> So I Compiled Petscii Robots SDL on my Windows PC via SDL which compiled the Version for Linux, But when I copied the Game onto my Steam Deck it wouldn't launch for some reason, I opened Konsole in the Folder where I copied the Game to, then when I tried to launch the Game again, it gave me this Error, "Segmentation fault (core dumped)". Is there a Fix for this? or is there something wrong with the Game's Code?

try `cd SDL` before launching the game with `../petrobots`

**Comment by zeropolis79** [comment]
In theory, is it possible to compile the SDL into a Windows executable?

**Comment by resolutezach1** [comment]
> > So I Compiled Petscii Robots SDL on my Windows PC via SDL which compiled the Version for Linux, But when I copied the Game onto my Steam Deck it wouldn't launch for some reason, I opened Konsole in the Folder where I copied the Game to, then when I tried to launch the Game again, it gave me this Error, "Segmentation fault (core dumped)". Is there a Fix for this? or is there something wrong with the Game's Code?
> 
> try `cd SDL` before launching the game with `../petrobots`

To My Surpise, that fixed it! Thanks! :D

**Comment by polluks** [comment]
> try `cd SDL` before launching the game with `../petrobots`

It's not very intuitive...

**Comment by nolemretaWxd** [comment]
> In theory, is it possible to compile the SDL into a Windows executable?

Yes, I've used MSYS2 MINGW64 to compile the game on Windows into Windows executable. Game runs, but with no sound, and way too fast.
